import type { NextPage } from 'next'
import { Presets, Align, Weight } from 'types/TextStyles'
import HeadText from '@element/HeadText/HeadText'
import BodyText from '@element/BodyText/BodyText'
import Head from 'next/head'
import Image from 'next/image'
import styles from './Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeadText
          preset={Presets.Hero}
          align={Align.Center}
          text="Welcome to COFIT TEST"
        />

        <BodyText 
          preset={Presets.Body1}
          align={Align.Center}
          text="Asli susah banget mau push up aja tu
          Kyk gimana caranya soalnya susah bgt dorong badan keatas
          Mungkina da yang bisa jawab"
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
